from __future__ import annotations

import datetime as dt
from pathlib import Path

from app.config import POLICIES_DIR


def generate_policy_pdf(policy: dict) -> Path:
    POLICIES_DIR.mkdir(parents=True, exist_ok=True)
    policy_id = policy.get("id", "demo")
    path = POLICIES_DIR / f"policy_{policy_id}.pdf"

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas

        c = canvas.Canvas(str(path), pagesize=A4)
        width, height = A4
        y = height - 72
        c.setFont("Helvetica-Bold", 18)
        c.drawString(72, y, "ACKO Insurance — Policy Certificate")
        y -= 36
        c.setFont("Helvetica", 11)
        lines = [
            f"Policy ID: {policy_id}",
            f"Vehicle: {policy.get('vehicle', 'N/A')}",
            f"Policy type: {policy.get('policy_type', 'Comprehensive')}",
            f"Premium: Rs. {policy.get('premium', 0):,.0f}",
            f"IDV: Rs. {policy.get('idv', 0):,.0f}",
            f"Status: {policy.get('status', 'active')}",
            f"Issued: {dt.date.today().isoformat()}",
            "",
            "This is a demo policy document generated by ACKO Insurance AI Platform.",
        ]
        for line in lines:
            c.drawString(72, y, line)
            y -= 18
        c.save()
        return path
    except ImportError:
        path = path.with_suffix(".txt")
        path.write_text(
            f"ACKO Policy {policy_id}\nVehicle: {policy.get('vehicle')}\nPremium: {policy.get('premium')}\n",
            encoding="utf-8",
        )
        return path
